# A sample Gemfile
source "https://rubygems.org"

gem "bundler"
gem "sinatra"
gem "sinatra-contrib"
gem "rack-cors"
gem "fuguta"
gem "rake"
gem "mysql2"
gem "sequel"
gem "unicorn"
gem "unicorn-worker-killer"

group :test do
  gem "rspec"
end